version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "my-sam-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-nxfcsbkvtwng"
s3_prefix = "my-sam-stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
